name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: Ajay-Lobo
      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "github-contribution-grid-snake.svg"
          message: "Generate Snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
